### PR TITLE
Created an audio cue file

### PR DESCRIPTION
**Pull request by coolpro9828**
just a bunch of files lmao

### CODE REVIEW

**Comment by neon443** [comment]
Please change the name to something informative as I cannot tell what has been changed without checking out and in away from home right now

**Comment by coolpro9828** [comment]
> Please change the name to something informative as I cannot tell what has been changed without checking out and in away from home right now Add a label as well

it's the name of the individual files, idk If it will mess up if I change it
Screenshot 2024-10-03 17 07 42

**Comment by neon443** [comment]
Don’t change the file name change the PR name
Or just tell me what u changed in one sentence and I’ll change it

**Comment by coolpro9828** [comment]
> Don’t change the file name change the PR name Or just tell me what u changed in one sentence and I’ll change it

how's this 
image

**Comment by neon443** [comment]
can u explain what uve added bc idk what one audio files gonna do

**Comment by coolpro9828** [comment]
I'm tryna add a bunch of files but I don't know how to do em all at once so I have to do it file by file and it gets really tedious 
edit: I found out how, I just need to upload them all at once rather than trying to manually copy and paste them

**Comment by coolpro9828** [comment]
delete the last commit I made, imma start a new one, this time I can actually do it easily

**Comment by neon443** [comment]
If u commit again it will be added to the pr

On 3 Oct 2024, at 20:24, coolpro9828 ***@***.***> wrote:

﻿

delete the last commit I made, imma start a new one, this time I can actually do it easily

**Pull request closed without merging**
